import { Internship, Testimonial } from './types';

export const internships: Internship[] = [
  {
    id: 1,
    title: 'Software Engineer Intern',
    company: 'TechCorp',
    location: 'San Francisco, CA',
    type: 'Full-time',
    logo: 'TC',
  },
  {
    id: 2,
    title: 'Product Design Intern',
    company: 'DesignHub',
    location: 'New York, NY',
    type: 'Part-time',
    logo: 'DH',
  },
  {
    id: 3,
    title: 'Marketing Intern',
    company: 'GrowthLabs',
    location: 'Remote',
    type: 'Remote',
    logo: 'GL',
  },
  {
    id: 4,
    title: 'Data Analyst Intern',
    company: 'DataWorks',
    location: 'Austin, TX',
    type: 'Full-time',
    logo: 'DW',
  },
  {
    id: 5,
    title: 'Frontend Developer Intern',
    company: 'WebFlow',
    location: 'Seattle, WA',
    type: 'Full-time',
    logo: 'WF',
  },
  {
    id: 6,
    title: 'UX Research Intern',
    company: 'UserFirst',
    location: 'Remote',
    type: 'Remote',
    logo: 'UF',
  },
  {
    id: 7,
    title: 'Business Analyst Intern',
    company: 'StrategyCo',
    location: 'Chicago, IL',
    type: 'Part-time',
    logo: 'SC',
  },
  {
    id: 8,
    title: 'Content Writer Intern',
    company: 'MediaPro',
    location: 'Los Angeles, CA',
    type: 'Part-time',
    logo: 'MP',
  },
  {
    id: 9,
    title: 'DevOps Engineer Intern',
    company: 'CloudTech',
    location: 'Remote',
    type: 'Remote',
    logo: 'CT',
  },
  {
    id: 10,
    title: 'Financial Analyst Intern',
    company: 'FinanceHub',
    location: 'Boston, MA',
    type: 'Full-time',
    logo: 'FH',
  },
  {
    id: 11,
    title: 'Graphic Design Intern',
    company: 'CreativeStudio',
    location: 'Portland, OR',
    type: 'Part-time',
    logo: 'CS',
  },
  {
    id: 12,
    title: 'Machine Learning Intern',
    company: 'AITech',
    location: 'San Jose, CA',
    type: 'Full-time',
    logo: 'AI',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    quote: 'FutureIntern helped me land my dream internship at a top tech company. The platform is easy to use and the opportunities are incredible!',
    name: 'Alex Johnson',
    role: 'Software Engineer Intern at Google',
    avatar: 'AJ',
  },
  {
    id: 2,
    quote: 'I found the perfect design internship through FutureIntern. The application process was smooth and I got hired within weeks!',
    name: 'Samantha Lee',
    role: 'UX Design Intern at Apple',
    avatar: 'SL',
  },
];
